// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unmbkwnxttheiorlxboa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVubWJrd254dHRoZWlvcmx4Ym9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Mjc0ODAsImV4cCI6MjA2NzQwMzQ4MH0.qle0ucFnEvB-x4VIDKmbdudSmyYYbZimiFvZ_HCOcnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});